// DISCLAIMER: For example purpose, these data are generated via ChatGPT 4

export const specialtySeed = [
  { "name": "Japanese", "imagePath": "images/japanese.jpg", "description": "Authentic Japanese cuisine with sushi and ramen." },
  { "name": "Asian", "imagePath": "images/asian.jpg", "description": "A mix of flavors from various Asian cultures." },
  { "name": "Chinese", "imagePath": "images/chinese.jpg", "description": "Traditional Chinese dishes like dim sum and Peking duck." },
  { "name": "Indian", "imagePath": "images/indian.jpg", "description": "Spiced curries, naan, and tandoori specialties." },
  { "name": "Mediterranean", "imagePath": "images/mediterranean.jpg", "description": "Healthy and flavorful dishes from the Mediterranean." },
  { "name": "Middle Eastern", "imagePath": "images/middle_eastern.jpg", "description": "Savory kebabs, hummus, and falafel delights." },
  { "name": "Vegan", "imagePath": "images/vegan.jpg", "description": "Plant-based meals for a healthy lifestyle." },
//   { "name": "Organic", "imagePath": "images/organic.jpg", "description": "Fresh, organic, and farm-to-table ingredients." },
  { "name": "Steakhouse", "imagePath": "images/steakhouse.jpg", "description": "Juicy steaks and grilled meats cooked to perfection." },
  { "name": "American", "imagePath": "images/american.jpg", "description": "Classic American comfort food and burgers." },
  { "name": "Alcohols", "imagePath": "images/alcohols.jpg", "description": "A selection of fine wines, beers, and spirits." },
  { "name": "French", "imagePath": "images/french.jpg", "description": "Elegant French cuisine with rich flavors." },
  { "name": "Sushi", "imagePath": "images/sushi.jpg", "description": "Freshly prepared sushi and sashimi plates." },
  { "name": "Korean", "imagePath": "images/korean.jpg", "description": "Bold Korean flavors including kimchi and BBQ." },
  { "name": "BBQ", "imagePath": "images/bbq.jpg", "description": "Smoked and grilled meats with savory sauces." },
  { "name": "Vegetarian", "imagePath": "images/vegetarian.jpg", "description": "Delicious and wholesome vegetarian meals." },
  { "name": "Mexican", "imagePath": "images/mexican.jpg", "description": "Spicy and flavorful Mexican tacos and burritos." },
  { "name": "Tacos", "imagePath": "images/tacos.jpg", "description": "Street-style tacos with fresh toppings." },
  { "name": "Seafood", "imagePath": "images/seafood.jpg", "description": "Fresh seafood dishes from the ocean." },
  { "name": "Italian", "imagePath": "images/italian.jpg", "description": "Classic Italian pasta, pizza, and more." },
  { "name": "Pasta", "imagePath": "images/pasta.jpg", "description": "A variety of pasta dishes with rich sauces." },
  { "name": "Fast Food", "imagePath": "images/fast_food.jpg", "description": "Quick and tasty fast food favorites." },
  { "name": "Grill", "imagePath": "images/grill.jpg", "description": "Flame-grilled meats and veggies." },
  { "name": "Greek", "imagePath": "images/greek.jpg", "description": "Fresh and flavorful Greek dishes." },
  { "name": "Gourmet", "imagePath": "images/gourmet.jpg", "description": "Fine dining with sophisticated flavors." },
  { "name": "Vietnamese", "imagePath": "images/vietnamese.jpg", "description": "Pho, banh mi, and other Vietnamese favorites." },
  { "name": "Noodles", "imagePath": "images/noodles.jpg", "description": "A variety of noodle dishes from Asia." },
//   { "name": "Ramen", "imagePath": "images/ramen.jpg", "description": "Rich and flavorful Japanese ramen bowls." },
  { "name": "Spanish", "imagePath": "images/spanish.jpg", "description": "Authentic Spanish cuisine with bold flavors." },
//   { "name": "Tapas", "imagePath": "images/tapas.jpg", "description": "Small Spanish plates for sharing." },
//   { "name": "Beer", "imagePath": "images/beer.jpg", "description": "A wide selection of craft and imported beers." },
  { "name": "Spicy", "imagePath": "images/spicy.jpg", "description": "Dishes packed with heat and bold spices." }
]
