// DISCLAIMER
// For example purpose, these data are generated via ChatGPT 4
export const userSeed = 
[
    {
        displayName: "Jono Surono",
        username: "jono100",
        email: "jonosurono@gourmets.com",
        password: "jono1234",
        imagePath: "jono100.webp",
        verifiedAt: new Date(),
        lastLoggedAt: undefined,
        deletedAt: undefined,
    },
    {
        displayName: "Tukiyem Wati",
        username: "tukiyem89",
        email: "tukiyemwati@gourmets.com",
        password: "tukiyem5678",
        imagePath: "tukiyem89.webp",
        verifiedAt: new Date(),
        lastLoggedAt: new Date(),
        deletedAt: undefined,
    },
    {
        displayName: "Parjo Herlambang",
        username: "parjo77",
        email: "parjoherlambang@gourmets.com",
        password: "parjo777",
        imagePath: "parjo77.webp",
        verifiedAt: new Date(),
        lastLoggedAt: undefined,
        deletedAt: undefined,
    },
    {
        displayName: "Sukijan Harsono",
        username: "sukijan2000",
        email: "sukijanharsono@gourmets.com",
        password: "sukijan2000pass",
        imagePath: "sukijan2000.webp",
        verifiedAt: new Date(),
        lastLoggedAt: new Date(),
        deletedAt: undefined,
    },
    {
        displayName: "Marmiyati",
        username: "marmi12",
        email: "marmiyati@gourmets.com",
        password: "marmi12secure",
        imagePath: "marmi12.webp",
        verifiedAt: new Date(),
        lastLoggedAt: undefined,
        deletedAt: undefined,
    },
    {
        displayName: "Sumirah Sari",
        username: "sumirah93",
        email: "sumirahsari@gourmets.com",
        password: "sumirah93key",
        imagePath: "sumirah93.webp",
        verifiedAt: new Date(),
        lastLoggedAt: undefined,
        deletedAt: undefined,
    },
    {
        displayName: "Budi Prastyo",
        username: "budi2023",
        email: "budiprastyo@gourmets.com",
        password: "budi2023lock",
        imagePath: "budi2023.webp",
        verifiedAt: new Date(),
        lastLoggedAt: new Date(),
        deletedAt: undefined,
    },
    {
        displayName: "Sriwijayaningsih",
        username: "sriwijaya88",
        email: "sriwijayaningsih@gourmets.com",
        password: "sriwijaya88safe",
        imagePath: "sriwijaya88.webp",
        verifiedAt: undefined,
        lastLoggedAt: new Date(),
        deletedAt: undefined,
    },
    {
        displayName: "Karto Suwandi",
        username: "karto56",
        email: "kartosuwandi@gourmets.com",
        password: "karto56secure",
        imagePath: "karto56.webp",
        verifiedAt: undefined,
        lastLoggedAt: new Date(),
        deletedAt: undefined,
    },
    {
        displayName: "Minartiadi",
        username: "minarti01",
        email: "minartiadi@gourmets.com",
        password: "minarti01pass",
        imagePath: "minarti01.webp",
        verifiedAt: new Date(),
        lastLoggedAt: undefined,
        deletedAt: undefined,
    }
]